modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="wilderness_oddesy_api"
version="0.8.1"
displayName="Wilderness Oddesy API"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator but mostly 99% made by me thunder"
authors="thunderrock424242"
description="this is a mod made for the modpack wilderness odessy. it has lots of tools and things in it."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.wilderness_oddesy_api]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wilderness_oddesy_api]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"




[[mixins]]
    config="mixins.wilderness_oddesy_api.json"